const fs = require('fs');
let content = fs.readFileSync('src/data/sppuSubjects.js', 'utf8');

const old = `  aids: {},
  entc: {},
  mechanicalEngineering: {},
  civilEngineering: {},
};`;

const replacement = `  aids: {
    semester3: [
      'Engineering Mathematics-III',
      'Data Structures & Algorithms',
      'Object Oriented Programming',
      'Statistics and Probability',
      'Digital Electronics and Logic Design',
      'Logic Design and Computer Organization',
    ],
    semester4: [
      'Database Management System',
      'Computer Graphics',
      'Linear Algebra',
      'Processor Architecture',
      'Software Engineering',
      'Theory of Computation',
    ],
    semester5: [
      'Machine Learning',
      'Operating Systems',
      'Design and Analysis of Algorithms',
      'Advanced Database Systems',
      'Human Computer Interaction',
      'Internet of Things',
    ],
    semester6: [
      'Deep Learning',
      'Data Science and Big Data Analytics',
      'Computer Networks and Security',
      'Cloud Computing',
      'Natural Language Processing',
      'Software Modeling and Design',
    ],
    semester7: [
      'Computer Vision',
      'Information Storage and Retrieval',
      'Mobile Computing',
      'High Performance Computing',
      'Multimedia Technology',
      'Smart Computing',
      'Bioinformatics',
      'Introduction to DevOps',
      'Wireless Communications',
    ],
    semester8: [
      'Distributed Systems',
      'Natural Language Processing',
      'Soft Computing',
      'Game Engineering',
      'Ethical Hacking and Security',
      'Augmented and Virtual Reality',
      'Business Analytics and Intelligence',
      'Blockchain Technology',
    ],
  },
  entc: {
    semester3: [
      'Engineering Mathematics-III',
      'Basic Electronics Engineering',
      'Network Analysis and Synthesis',
      'Semiconductor Devices and Circuits',
      'Digital Electronics and Logic Design',
      'Electromagnetic Field Theory',
    ],
    semester4: [
      'Signals and Systems',
      'Analog Communication Engineering',
      'Microprocessor and Interfacing',
      'Probability and Statistics',
      'Database Management System',
      'Computer Organization',
    ],
    semester5: [
      'Digital Signal Processing',
      'Digital Communication Engineering',
      'Embedded Systems',
      'Theory of Computation',
      'Computer Networks',
      'Internet of Things and Embedded Systems',
    ],
    semester6: [
      'Information Theory and Coding',
      'VLSI Design',
      'Antenna and Wave Propagation',
      'Software Engineering',
      'Data Science and Big Data Analytics',
      'Cloud Computing',
    ],
    semester7: [
      'Wireless and Mobile Communications',
      'Optical Communication',
      'Human Computer Interface',
      'Design and Analysis of Algorithms',
      'Cyber Security',
      'Digital Image Processing',
    ],
    semester8: [
      'Satellite Communication',
      'Microwave Engineering',
      'Deep Learning',
      'Natural Language Processing',
      'Soft Computing',
      'Business Analytics and Intelligence',
    ],
  },
  mechanicalEngineering: {
    semester3: [
      'Engineering Mathematics-III',
      'Thermodynamics',
      'Mechanics of Materials',
      'Machine Design',
      'Manufacturing Processes',
      'Fluid Mechanics',
    ],
    semester4: [
      'Heat and Mass Transfer',
      'Theory of Machines',
      'Design of Machine Elements',
      'Manufacturing Technology',
      'Engineering Metrology',
      'Probability and Statistics',
    ],
    semester5: [
      'Internal Combustion Engines',
      'Refrigeration and Air Conditioning',
      'Dynamics of Machinery',
      'Finite Element Method',
      'Operations Research',
      'Computer Graphics',
    ],
    semester6: [
      'Automobile Engineering',
      'Power Plant Engineering',
      'Hydraulic Machines and Systems',
      'Machine Tool Technology',
      'Robotics',
      'Design of Mechanical Systems',
    ],
    semester7: [
      'Composite Materials',
      'Noise and Vibration Control',
      'Renewable Energy Systems',
      'Rapid Prototyping',
      'Advanced Manufacturing',
      'Project Management',
    ],
    semester8: [
      'Total Quality Management',
      'Entrepreneurship Development',
      'Maintenance Engineering',
      'Condition Monitoring',
      'Computational Fluid Dynamics',
      'Business Analytics and Intelligence',
    ],
  },
  civilEngineering: {
    semester3: [
      'Engineering Mathematics-III',
      'Structural Analysis',
      'Surveying and Levelling',
      'Building Construction',
      'Concrete Technology',
      'Fluid Mechanics',
    ],
    semester4: [
      'Structural Mechanics',
      'Highway Engineering',
      'Soil Mechanics',
      'Construction Management',
      'Environmental Engineering',
      'Probability and Statistics',
    ],
    semester5: [
      'Design of Steel Structures',
      'Design of Concrete Structures',
      'Transportation Engineering',
      'Geotechnical Engineering',
      'Water Resources Engineering',
      'Building Services',
    ],
    semester6: [
      'Bridge Engineering',
      'Foundation Engineering',
      'Environmental Impact Assessment',
      'Project Management',
      'Estimation and Costing',
      'GIS and Remote Sensing',
    ],
    semester7: [
      'Earthquake Engineering',
      'Prestressed Concrete',
      'Highway and Pavement Design',
      'Sanitary Engineering',
      'Construction Safety',
      'Structural Dynamics',
    ],
    semester8: [
      'Advanced Structural Design',
      'Tunneling and Underground Structures',
      'Infrastructure Management',
      'Building Information Modeling',
      'Entrepreneurship Development',
      'Computational Mechanics',
    ],
  },
};`;

if (content.includes(old)) {
  content = content.replace(old, replacement);
  fs.writeFileSync('src/data/sppuSubjects.js', content);
  console.log('SUCCESS: sppuSubjects.js updated');
} else {
  console.log('ERROR: old pattern not found');
}